language: perl

sudo: false

perl:
    - "5.26"

addons:
    apt:
        packages:
            - gzip
            - bzip2
            - zip
            - unzip
            
install:
    - "export PATH=$PWD:$PATH"

script:
    - "! any2fasta"
    - "any2fasta -v"
    - "any2fasta -h"
    - "! any2fasta -x"
    - "any2fasta /dev/null 2>&1 | grep 'ERROR'"
    - "any2fasta test.noseq.gff 2>&1 | grep 'ERROR'"
    - "any2fasta test.gbk | grep -m 3 '^>'"
    - "any2fasta test.gff | grep -m 3 '^>'"
    - "any2fasta test.fna | grep -m 3 '^>'"
    - "any2fasta test.gfa | grep -m 3 '^>'"
    - "any2fasta test.fq  | grep -m 3 '^>'"
    - "any2fasta test.embl | grep -m 3 '^>'"
    - "any2fasta test.clw  | grep -m 3 '^>'"
    - "any2fasta test.sth  | grep -m 3 '^>'"
    - "any2fasta    test.fna | grep 'CRYANT'"
    - "any2fasta -n test.fna | grep 'CNNANT'"
    - "any2fasta test.gfa | grep '^>24292$'"
    - "any2fasta test.fq | grep '^>ERR1163317.999'"
    - "any2fasta test.clw | grep '^>O83071'"
    - "any2fasta test.sth | grep '^>gene03'"
    - "any2fasta -l test.gbk | grep 'taagaatgagtagaaggttttga'"
    - "any2fasta -u test.gbk | grep 'TAAGAATGAGTAGAAGGTTTTGA'"
    - "any2fasta -u test.embl | grep 'K02675'"
    - "any2fasta -q -l -n test.fq | wc -l | grep '^2000$'"
    - "any2fasta -f '%v' test.gbk  | grep -m 1 -F '>NZ_AHMY02000075.1'"
    - "any2fasta -f '%o' test.gbk  | grep -m 1 -F '>Leptospira'"
    - "any2fasta - < test.gbk  | grep -m 1 -F 'NZ_AHMY02000074'"
    - "gzip -c test.gbk | any2fasta - | grep -m 1 -F 'NZ_AHMY02000074'"
    - "bzip2 -c test.gbk | any2fasta - | grep -m 1 -F 'NZ_AHMY02000074'"
    - "zip test.gbk.zip test.gbk"
    - "any2fasta test.gbk.zip | grep -m 1 -F 'NZ_AHMY02000074'"
    - echo -e ">1\nA\n\n>2\nT\n" | ./any2fasta -q - | wc -l | grep '^4$'
